spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos # Instancia del microservicio: Mediante balanceo de carga podamos acceder a este recurso
        predicates: 
          - Path=/api/productos/**
        filters: 
          - StripPrefix=2
      - id: servicio-items
        uri: lb://servicio-items # Instancia del microservicio: Mediante balanceo de carga podamos acceder a este recurso
        predicates: 
          - Path=/api/items/**
        filters: 
          - StripPrefix=2
